name: Go

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mysql: ['mysql:5.6', 'mysql:5.7', 'mysql:latest']
        go: ['1', '1.12', '1.13']

    services:
      mysql:
        image: ${{ matrix.mysql }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Env
        run: go env

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -race ./...
        env:
          DB_TEST_URI: "root@tcp(localhost:${{ job.services.mysql.ports[3306] }})/test?"
          DB_EXAMPLE_CLIENT_URI: "root@tcp(localhost:${{ job.services.mysql.ports[3306] }})/test?"
          DB_EXAMPLE_SERVER_URI: "root@tcp(localhost:${{ job.services.mysql.ports[3306] }})/test?"
