name: Go

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image:  golang:alpine

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Env
        run: go env

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: go test ./...
        env:
          DB_TEST_URI: "root@tcp(localhost:${{ job.services.mysql.ports[3306] }})/test?"
